### ISSUE TITLE
minified_javascript is generated but not displayed

### ISSUE THREAD

**Issue by Cruiser13** [dpfaffenbauer/pimcore-minify#1]
I successfully installed this plugin in Pimcore and it seems to work. I do see a lot of minified_javascript files in my /tmp directory. But the website iteself does not change, it does still have the uncompressed .JS files in the source code.

Am I missing something?

There are no minified_css files in /tmp although there are .CSS files used in the layout.

**Comment by dpfaffenbauer** [comment]
Can you give me a Link?

**Comment by Cruiser13** [comment]
Sadly no, it's on my local development server.

**Comment by dpfaffenbauer** [comment]
oh ok. the minify only works when disabled the debug mode and your not logged in to pimcore. have you tried that?

**Comment by Cruiser13** [comment]
Thanks, deactivating debugging did the trick. You might want to add this to the Readme file.

Now I just have to take a look at jQuery which failes to load minified (ReferenceError: $ is not defined)...

**Comment by dpfaffenbauer** [comment]
Do you have any inline Javascript? 
Take a look at the minified JS and check if the order is right.

**Comment by Cruiser13** [comment]
Inline JS does exist (while developing). The order is right.

**Comment by dpfaffenbauer** [comment]
your inline js is the problem. Minify will add the JS to the bottom of the body tag. so, at the time your inline js is called, jquery is not yet loaded.

**Comment by dpfaffenbauer** [comment]
i finally fixed your problem. all inline js will now minimized and added to the bottom.

**Comment by Cruiser13** [comment]
Great job, thanks.
