### ISSUE TITLE
Minify is generating invalid markup (HTML validation fails) because of async

### ISSUE THREAD

**Issue by Cruiser13** [dpfaffenbauer/pimcore-minify#4]
If minify is used, the following code will be generated by the plugin (for example):
`<script type="text/javascript" async="false" src="/website/var/tmp/minified_javascript_0ea1ea04310d23b1aec1c1b43e9dc116.js"></script>`

This does cause the following error in HTML Validation (W3C):
**Bad value “false” for attribute “async” on element “script”.**

The HTML 5 specification does accept something like this:
`<script type="text/javascript" async src="/16.js"></script>`
But it does not allow the opposite.

I'm not sure how to fix that without loosing the valid async functionality.

**Comment by dpfaffenbauer** [comment]
This plugin is more or less deprecated. There are now much better options for minimizing css/js. Google mod pagespeed for example.
