### ISSUE TITLE
Require /Minify/vendor/autoload.php not found

### ISSUE THREAD

**Issue by Yivan** [dpfaffenbauer/pimcore-minify#5]
Thanks again for this great plugin : )

Just one problem when testing it:
This line https://github.com/dpfaffenbauer/pimcore-minify/blob/master/lib/Minify/Plugin.php#L15 send an error as the file doesn't exist.

By commenting it, all seems to work (as autoload is handled by composer).
So maybe it could be removed from the code ?

**Comment by dpfaffenbauer** [comment]
This plugin is more or less deprecated. There are now much better options for minimizing css/js. Google mod pagespeed for example.

**Comment by Yivan** [comment]
Thanks. Maybe an indication that is is deprecated could be added in the reame.md, so next developper could be informed.

Yes pagespeed is great, I used it on some project and it handle all-in-one optimisations : )
